yolo_model:

  config_file:
    name: yolov3custom.cfg
  weight_file:
    name: yolov3custom.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - QR
      - FireExtinguisher
      - Barrel
      - HazmatOxidizer
      - HazmatRadioactive
      - HazmatInhalation
      - HazmatNonFlammableGas
      - HazmatInfectiousSubstance
      - HazmatCorrosive
      - HazmatExplosive
      - HazmatSpontCombustible
