classification:
  model: "/home/serdar/catkin_ws/src/rtg_proje/scripts/classifier/model/yolo.h5"
  anchors: "/home/serdar/catkin_ws/src/rtg_proje/scripts/classifier/model/tiny_yolo_anchors.txt"
  classes: '/scripts/classifier/model/classes.txt'
